export const USER_REGISTERATION_REQUEST = "USER_REGISTERATION_REQUEST"
export const USER_REGISTERATION_SUCCESS = "USER_REGISTERATION_SUCCESS"
export const USER_REGISTERATION_FAIL = "USER_REGISTERATION_FAIL"