export const USER_REGISTERATION_REQUEST = "USER_REGISTERATION_REQUEST"
export const USER_REGISTERATION_SUCCESS = "USER_REGISTERATION_SUCCESS"
export const USER_REGISTERATION_FAIL = "USER_REGISTERATION_FAIL"

export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST"
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS"
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL"
export const USER_SIGNOUT = "USER_SIGNOUT" 

export const USER_DETAIL_REQUEST = "USER_DETAIL_REQUEST"
export const USER_DETAIL_SUCCESS = "USER_DETAIL_SUCCESS"
export const USER_DETAIL_FAIL = "USER_DETAIL_FAIL"